apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: persons-finder-pdb
  namespace: default
  labels:
    app: persons-finder
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: persons-finder
